spring:
  application:
    name: discovery
  config:
    activate:
      on-profile: dev

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: ${PORT:8761}
  servlet:
    context-path: /discovery

management:
  endpoints:
    web:
      exposure:
        include: "*"
