spring:
  application:
    name: discovery
  jackson:
    time-zone: America/Sao_Paulo
  timezone: America/Sao_Paulo

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    prefer-ip-address: true

server:
  port: ${PORT:8761}

management:
  endpoints:
    web:
      exposure:
        include: "*"
---
spring:
  config:
    activate:
      on-profile: prod
server:
  port: ${PORT}
